/** Emit a self-contained, typed API client the trader drops into their app. The
 *  generated client reads its key from the environment and consumes the API at
 *  runtime (the MCP is build-time only). Generated source uses string
 *  concatenation (no template literals) so it embeds cleanly here. */

export function generateTypes(): string {
  return [
    "// Generated by @edgecute/mcp — Edgecute Backtest API types.",
    "export interface EquityPoint { time: number; value: number; }",
    "export interface AggregateMetrics { [k: string]: number | null; }",
    "export interface Trade {",
    "  ticker: string; date: string; entry_price?: number; exit_price?: number;",
    "  pnl?: number; return_pct?: number; direction?: string; exit_reason?: string;",
    "  r_multiple?: number | null; [k: string]: unknown;",
    "}",
    "export interface TradesPage {",
    "  items: Trade[];",
    "  page: { limit: number; returned: number; total: number; next_cursor: string | null };",
    "  export_url?: string | null;",
    "}",
    "export interface DayResult { ticker: string; date: string; [k: string]: unknown; }",
    "export interface BacktestResult {",
    "  aggregate_metrics?: AggregateMetrics;",
    "  global_equity?: EquityPoint[];",
    "  global_drawdown?: EquityPoint[];",
    "  day_results?: DayResult[];",
    "  trades?: TradesPage;",
    "}",
    "export interface JobStatus {",
    "  job_id: string;",
    "  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';",
    "  meta?: Record<string, unknown>;",
    "  result?: BacktestResult;",
    "}",
    "",
  ].join("\n");
}

export function generateApiClient(): string {
  const lines = [
    "// Generated by @edgecute/mcp. Runtime client for the Edgecute Backtest API.",
    "// The MCP is build-time only; THIS file is what your app uses at runtime.",
    "import type { JobStatus, BacktestResult } from './edgecuteTypes';",
    "",
    "export class EdgecuteApiError extends Error {",
    "  constructor(public code: string, message: string, public status: number, public details?: unknown) {",
    "    super(message);",
    "    this.name = 'EdgecuteApiError';",
    "  }",
    "}",
    "",
    "export interface EdgecuteClientOptions {",
    "  apiKey: string;",
    "  apiBase?: string;",
    "}",
    "",
    "export class EdgecuteClient {",
    "  private base: string;",
    "  private apiKey: string;",
    "  constructor(opts: EdgecuteClientOptions) {",
    "    this.apiKey = opts.apiKey;",
    "    this.base = (opts.apiBase || 'https://api.edgecute.com/v1').replace(/\\/+$/, '');",
    "  }",
    "  private async req<T>(method: string, path: string, body?: unknown): Promise<T> {",
    "    const res = await fetch(this.base + path, {",
    "      method,",
    "      headers: { Authorization: 'Bearer ' + this.apiKey, 'Content-Type': 'application/json' },",
    "      body: body === undefined ? undefined : JSON.stringify(body),",
    "    });",
    "    if (!res.ok) {",
    "      let code = 'api_error'; let message = 'Error ' + res.status; let details: unknown;",
    "      try { const d = await res.json() as any; if (d && d.error) { code = d.error.code || code; message = d.error.message || message; details = d.error.details; } } catch {}",
    "      throw new EdgecuteApiError(code, message, res.status, details);",
    "    }",
    "    return await res.json() as T;",
    "  }",
    "  runBacktest(body: unknown): Promise<JobStatus> { return this.req('POST', '/backtests', body); }",
    "  getBacktest(jobId: string): Promise<JobStatus> { return this.req('GET', '/backtests/' + encodeURIComponent(jobId)); }",
    "  validateStrategy(strategy: unknown) { return this.req('POST', '/strategies/validate', strategy); }",
    "  previewUniverse(spec: unknown) { return this.req('POST', '/universe/preview', spec); }",
    "  listIndicators(category?: string) { return this.req('GET', '/catalog/indicators' + (category ? '?category=' + encodeURIComponent(category) : '')); }",
    "  intraday(jobId: string, ticker: string, date: string) { return this.req('GET', '/backtests/' + encodeURIComponent(jobId) + '/intraday?ticker=' + encodeURIComponent(ticker) + '&date=' + encodeURIComponent(date)); }",
    "}",
    "",
    "export type { JobStatus, BacktestResult };",
    "",
  ];
  return lines.join("\n");
}

export interface GeneratedClientFiles {
  files: Array<{ path: string; content: string }>;
  instructions: string;
}

export function generateApiClientFiles(targetDir = "src/lib/edgecute"): GeneratedClientFiles {
  const dir = targetDir.replace(/\/+$/, "");
  return {
    files: [
      { path: `${dir}/edgecuteTypes.ts`, content: generateTypes() },
      { path: `${dir}/edgecuteClient.ts`, content: generateApiClient() },
    ],
    instructions:
      `Cliente tipado escrito en ${dir}/. Úsalo en runtime:\n` +
      `  const c = new EdgecuteClient({ apiKey: process.env.EDGECUTE_API_KEY! });\n` +
      `  const job = await c.runBacktest({ universe: { dataset_ref: '...' }, strategy: {...}, include: ['metrics','equity'] });`,
  };
}
